#!/bin/bash

python3 -m build
twine check dist/*
twine upload --repository testpypi dist/*
echo -e "\ncheck https://test.pypi.org/project/curifactory\n"
read -p "press any key to continue..."
twine upload dist/*
